server: {port: 8083}
spring:
  datasource: {url: 'jdbc:mysql://47.106.243.172:3306/books?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai',
    username: books, password: books!8888}
mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: xyz.zinglizingli.books.po
  configuration: {log-impl: org.apache.ibatis.logging.stdout.StdOutImpl}
mysql: {charset: utf8mb4}
books: {lowestScore: 9.0}
crawl:
  website: {type: '4'}
  soft-novel: '1'
  manhua: '1'
logging: {config: 'classpath:logback-boot.xml'}
