server: {port: 8083}
spring:
  datasource: {url: 'jdbc:mysql://47.106.243.172:3306/novel?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai',
    username: novel, password: novel!8888}
mybatis:
  mapper-locations: classpath:mybatis/mapping/*.xml
  type-aliases-package: xyz.zinglizingli.books.po
  configuration: {log-impl: org.apache.ibatis.logging.stdout.StdOutImpl}
mysql: {charset: utf8mb4}
books: {lowestScore: '9.0'}
crawl:
  website: {type: '2'}
  soft-novel: '0'
  manhua: '0'
